FROM continuumio/miniconda3 AS conda

FROM openiss/openiss-cuda-base:F22-01 AS buildbase
COPY --from=conda /opt/conda /opt/conda

#RUN apt-get install -y nvidia-utils

RUN /opt/conda/bin/conda install jupyter -y --quiet \
    && mkdir /opt/notebooks

CMD /bin/bash
