FROM ubuntu:20.04

RUN apt-get update --fix-me
RUN apt-get upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing gnupg wget build-essential

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends bash xserver-xorg-dev libx11-dev libgl1-mesa-dev libglew-dev libglfw3-dev libglm-dev cmake gcc

CMD /bin/bash
