FROM ubuntu:20.04

RUN apt-get update --fix-missing
RUN apt-get upgrade -y

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends --fix-missing gnupg wget build-essential bash cmake gcc git make \
    && apt-get clean

CMD /bin/bash
