FROM openiss/openiss-cuda-base:F22-01

WORKDIR cuda-samples/Samples/1_Utilities/deviceQuery

# 90 breaks currently in nvcc in 11.7
RUN make SMS="35 37 50 52 60 61 70 75 80 86"

CMD ./deviceQuery
