FROM nvidia/cuda:11.7.1-devel-ubuntu20.04

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git make mesa-common-dev libglu1-mesa-dev freeglut3-dev gdb

WORKDIR /code/nvidia

RUN git clone https://github.com/NVIDIA/cuda-samples.git

WORKDIR cuda-samples/Samples/5_Domain_Specific/simpleGL

RUN make SMS="35 37 50 52 60 61 70 75 80 86"

CMD ./simpleGL
