FROM nvidia/cuda:11.7.1-devel-ubuntu20.04

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git make mesa-common-dev libglu1-mesa-dev freeglut3-dev gdb

WORKDIR /code/nvidia

#RUN git clone https://github.com/NVIDIA/cuda-samples.git
COPY cuda-samples cuda-samples

WORKDIR cuda-samples/Samples/5_Domain_Specific/simpleGL

RUN make

CMD ./simpleGL
