FROM openiss/openiss-ubuntu20-base:F22-01

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends xserver-xorg-dev libx11-dev libgl1-mesa-dev libglew-dev libglfw3-dev libglm-dev \
    && apt-get clean

CMD /bin/bash
