FROM openiss/openiss-opengl-base:F22-01

WORKDIR /usr/src/OpenGL

RUN apt-get install -y --reinstall ca-certificates 
RUN apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

RUN git clone --depth 1 https://github.com/OpenISS/OpenGL-Skeleton-Framework.git

WORKDIR ./OpenGL-Skeleton-Framework
RUN cmake -S . -B cmake-build
RUN cmake --build cmake-build --target install

CMD ./dist/SunRay
